// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateQuestions(arg1:number,arg2:number):Promise<Array<main.Question>>;

export function Greet(arg1:string):Promise<string>;
